""" Constants Module
    ----------------

    Contains constants shared by multiple algorithms.
"""


NUM_SETS = 5
CONF_QT = 0.975
RANK_SIZE = 5
REP = 3


REVIEW_FEATS = {
  'www': ['num_tokens', 'num_sents', 'uni_ratio', 'avg_sent',
    'cap_sent', 'noun_ratio', 'adj_ratio', 'comp_ratio', 'verb_ratio',
    'adv_ratio', 'fw_ratio', 'sym_ratio', 'num_ratio', 'punct_ratio', 'kl',
    'pos_ratio', 'neg_ratio'],
  'sel': ['num_tokens', 'uni_ratio', 'noun_ratio', 'sym_ratio', 'fw_ratio',
    'kl', 'avg_sent', 'punct_ratio'],
  'cap': ['num_tokens', 'num_sents', 'uni_ratio', 'avg_sent',
    'cap_sent', 'noun_ratio', 'adj_ratio', 'comp_ratio', 'verb_ratio',
    'adv_ratio', 'fw_ratio', 'sym_ratio', 'num_ratio', 'punct_ratio', 'kl',
    'pos_ratio', 'neg_ratio'],
  'all': ['num_tokens', 'num_sents', 'uni_ratio', 'avg_sent',
    'cap_sent', 'noun_ratio', 'adj_ratio', 'comp_ratio', 'verb_ratio',
    'adv_ratio', 'fw_ratio', 'sym_ratio', 'num_ratio', 'punct_ratio', 'kl',
    'pos_ratio', 'neg_ratio'],
  'svr_top10': ['noun_ratio', 'uni_ratio', 'sym_ratio', 'punct_ratio',
    'verb_ratio', 'comp_ratio', 'kl'],
  'spear_top10': ['num_tokens', 'num_sents', 'uni_ratio'],
  'spear_top10m': ['num_tokens', 'uni_ratio'],
  'spear_top10': ['num_tokens', 'uni_ratio'],
  'new_sel': ['num_tokens', 'uni_ratio'],
  'ig_top5': ['num_tokens', 'num_sents', 'uni_ratio'],
  'ig_top10': ['num_tokens', 'num_sents', 'uni_ratio'],
  'spear_top1': ['num_tokens'],
  'spear_top2': ['num_tokens', 'num_sents'],
  'spear_top3': ['num_tokens', 'num_sents', 'uni_ratio'],
  'spear_top4': ['num_tokens', 'num_sents', 'uni_ratio'],
  'spear_top5': ['num_tokens', 'num_sents', 'uni_ratio'],
  'spear_top5m': ['num_tokens', 'uni_ratio'],
  'spear_top6': ['num_tokens', 'num_sents', 'uni_ratio'],
  'spear_top7': ['num_tokens', 'num_sents', 'uni_ratio'],
  'spear_top8': ['num_tokens', 'num_sents', 'uni_ratio'],
  'spear_top9': ['num_tokens', 'num_sents', 'uni_ratio']
}
AUTHOR_FEATS = {
  'www': ['num_reviews', 'avg_rating', 'num_trustors', 'num_trustees',
    'pagerank'],
  'sel': ['num_trustors'],
  'cap': ['num_reviews', 'avg_rating', 'num_trustors', 'num_trustees',
    'pagerank'],
  'all': ['num_reviews', 'avg_rating', 'num_trustors', 'num_trustees',
    'pagerank', 'num_votes_rec', 'num_votes_giv', 'sd_rating', 'sd_help_rec',
    'sd_help_giv', 'avg_rel_rating', 'avg_help_rec', 'avg_help_giv',
    'avg_rel_help_giv', 'avg_rating_sim', 'avg_help_giv_sim',
    'avg_rating_dir_net', 'avg_help_giv_tru_net'],
  'svr_top10': [],
  'spear_top10': ['num_trustees', 'num_trustors', 'num_reviews'],
  'spear_top10m': ['num_trustees', 'num_trustors', 'num_reviews'],
  'new_sel': ['num_trustees', 'num_trustors', 'num_reviews'],
  'ig_top5': ['pagerank', 'num_trustees'],
  'ig_top10': ['pagerank', 'num_trustees'],
  'spear_top1': [],
  'spear_top2': [],
  'spear_top3': [],
  'spear_top4': [],
  'spear_top5': ['num_trustees'],
  'spear_top5m': ['num_trustees'],
  'spear_top6': ['num_trustees', 'num_trustors'],
  'spear_top7': ['num_trustees', 'num_trustors'],
  'spear_top8': ['num_trustees', 'num_trustors'],
  'spear_top9': ['num_trustees', 'num_trustors']
}
VOTER_FEATS = {
  'www': [],
  'sel': ['avg_help_giv', 'avg_help_giv_tru_net'],
  'cap': ['num_trustors', 'num_trustees', 'pagerank', 'avg_rating',
    'avg_rating_dir_net', 'avg_rating_sim', 'avg_help_giv', 'avg_help_giv_sim', 
    'avg_help_giv_tru_net'],
  'all': ['num_reviews', 'avg_rating', 'num_trustors', 'num_trustees',
    'pagerank', 'num_votes_rec', 'num_votes_giv', 'sd_rating', 'sd_help_rec',
    'sd_help_giv', 'avg_rel_rating', 'avg_help_rec', 'avg_help_giv',
    'avg_rel_help_giv', 'avg_rating_sim', 'avg_help_giv_sim',
    'avg_rating_dir_net', 'avg_help_giv_tru_net'],
  'svr_top10': ['avg_help_giv'],
  'spear_top10': ['avg_help_giv'],
  'spear_top10m': ['avg_help_giv'],
  'new_sel': ['avg_help_giv'],
  'ig_top5': [],
  'ig_top10': ['avg_help_giv', 'pagerank', 'avg_rating_dir_net',
    'avg_rating_sim', 'avg_help_giv_sim'],
  'spear_top1': [],
  'spear_top2': [],
  'spear_top3': [],
  'spear_top4': ['avg_help_giv'],
  'spear_top5': ['avg_help_giv'],
  'spear_top5m': ['avg_help_giv'],
  'spear_top6': ['avg_help_giv'],
  'spear_top7': ['avg_help_giv'],
  'spear_top8': ['avg_help_giv'],
  'spear_top9': ['avg_help_giv']
}
SIM_FEATS = {
  'www': [],
  'sel': ['jacc_rated', 'common_rated'],
  'cap': ['common_rated', 'jacc_rated', 'cos_ratings', 'pear_ratings',
    'diff_avg_ratings', 'diff_max_ratings', 'diff_min_ratings'],
  'all': ['common_rated', 'jacc_rated', 'cos_ratings', 'pear_ratings',
    'diff_avg_ratings', 'diff_max_ratings', 'diff_min_ratings'],
  'svr_top10': [],
  'svr_top10m': [],
  'new_sel': ['diff_trustors', 'diff_reviews', 'diff_pagerank', 'diff_close',
    'diff_eigen'],
  'spear_top10': [],
  'ig_top5': [],
  'ig_top10': [],
  'spear_top1': [],
  'spear_top2': [],
  'spear_top3': [],
  'spear_top4': [],
  'spear_top5': [],
  'spear_top5m': [],
  'spear_top6': [],
  'spear_top7': [],
  'spear_top8': [],
  'spear_top9': []
}
CONN_FEATS = {
  'www': [],
  'cap': ['jacc_trustees', 'jacc_trustors', 'adamic_adar_trustees',
    'adamic_adar_trustors', 'katz'],
  'sel': ['jacc_trustees', 'adamic_adar_trustees', 'adamic_adar_trustors'], 
  'all': ['jacc_trustees', 'jacc_trustors', 'adamic_adar_trustees',
    'adamic_adar_trustors', 'katz'],
  'svr_top10': ['jacc_trustors', 'adamic_adar_trustors'],
  'spear_top10': ['jacc_trustees', 'adamic_adar_trustees',
    'adamic_adar_trustors'],
  'spear_top10m': ['jacc_trustees', 'adamic_adar_trustees',
    'adamic_adar_trustors'],
  'new_sel': ['jacc_trustees', 'adamic_adar_trustees', 'adamic_adar_trustors', 
    'voter_trust',  'author_trust', 'inv_from_vot_path', 'inv_from_aut_path'],
  'ig_top5': [],
  'ig_top10': [],
  'spear_top1': [],
  'spear_top2': [],
  'spear_top3': [],
  'spear_top4': [],
  'spear_top5': [],
  'spear_top5m': [],
  'spear_top6': ['jacc_trustees'],
  'spear_top7': ['jacc_trustees'],
  'spear_top8': ['jacc_trustees', 'adamic_adar_trustees'],
  'spear_top9': ['jacc_trustees', 'adamic_adar_trustees',
      'adamic_adar_trustors']
}
